What does the following print out? - 500. g() try's to run f, f is an empty function and falis throwing 500, g catches the err and then console logs it.

function f() {
    throw 500;
}

function g() {
    try{
        f();
    } catch(err) {
        console.log(err);
    }
}

g();
